###**INTRODUCTION**
Numpy là một **thư viện** của python. Đây là thư viện **cốt lõi** cho scientific computing. Bao gồm các tác vụ xử lý như: mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation, v.v...

So với List chúng tôi sử dụng numpy bởi 3 lý do sau đây:

*   Bộ nhớ ít hơn
*   Nhanh
*   Tiện lợi

Các phần tử trong numpy có cùng **kiểu dữ liệu**. Và được lập chỉ mục bởi 1 tuple số nguyên dương.
*(Tham khảo từ bài của anh Văn Quang)*

###**NỘI DUNG**
  1. Data type
  2. Khởi tạo
  3. Truy xuất dữ liệu
  4. Indexing
  5. Phép toán và các hàm

####**1. Data type(dtype)**



Dưới đây là kiểu dữ liệu của từng phần tử trong numpy:



![](https://miro.medium.com/max/831/1*Ug1HDdt2DIPAWungbOSMCA.png)


####**2. Khởi tạo**

Các phần khởi tạo quan trọng trong Numpy

1. np.**array**(list): Khởi tạo **từ 1 list**
2. np.**arange**(begin=0,end,step=1): khởi tạo dãy 
3. np.**zeros**(dim): Khởi tạo **toàn số 0** theo Dimensions
4. np.**ones**(dim): Khởi tạo **toàn số 1** theo Dimensions
5. np.**full**(dim, value): Khởi tạo **toàn số value** theo Dimensions
6. np.**eye**(n): khởi tạo **ma trận đơn vị** kích thước nxn
7. np.**linspace**(start, stop, num=50): khởi tạo dãy đều nhau
8. np.**copy**(array): khởi tạo bằng cách **copy từ array** khác
9. np.**reshape**(dim): khởi tạo từ **array vs dimensions**
10. Các hàm random

Lưu ý: 
*   **Dim**ensions là 1 tuple. Nếu 1 chiều thì có thể dùng 1 scalar(số)
*   Khi khởi tạo thì mặc định: float64 và int64


1. np.**array**(list): Khởi tạo **từ 1 list**

In [ ]:
import numpy as np

print("\n 1.np.array([1,2,3,4]) ")
arr1 = np.array([1,2,3,4])
print(arr1)


 1.np.array([1,2,3,4]) 
[1 2 3 4]


2. np.**arange**(begin=0,end,step=1): khởi tạo dãy 

In [ ]:
import numpy as np

print("\n 2.np.arange(10)")
arr2 = np.arange(10)
print(arr2)


 2.np.arange(10)
[0 1 2 3 4 5 6 7 8 9]


3. np.**zeros**(dim): Khởi tạo **toàn số 0** theo Dimensions


In [ ]:
import numpy as np

print("\n 3.np.zeros((2,3)) ")
arr3_zeros = np.zeros((2,3))
print(arr3_zeros)


 3.np.zeros((2,3)) 
[[0. 0. 0.]
 [0. 0. 0.]]


4. np.**ones**(dim): Khởi tạo **toàn số 1** theo Dimensions

In [ ]:
import numpy as np

print("\n 4.np.ones(10) ")
arr4_ones = np.ones(10)
print(arr4_ones)


 4.np.ones(10) 
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


5. np.**full**(dim, value): Khởi tạo **toàn số value** theo Dimensions

In [ ]:
import numpy as np

print("\n 5.np.full((3,3), 2) ")
arr5_full = np.full((3,3), 2)
print(arr5_full)


 5.np.full((3,3), 2) 
[[2 2 2]
 [2 2 2]
 [2 2 2]]


6. np.**eye**(n): khởi tạo **ma trận đơn vị** kích thước nxn

In [ ]:
import numpy as np

print("\n 6.np.eye(4)")
arr6_eye = np.eye(4)
print(arr6_eye)


 6.np.eye(3)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


7. np.**linspace**(start, stop, num=50): khởi tạo dãy đều nhau

In [ ]:
import numpy as np

print("\n 7.np.linspace(0, 5) ")
arr7_linspace = np.linspace(0, 5, 6)
print(arr7_linspace)


 7.np.linspace(0, 5) 
[0. 1. 2. 3. 4. 5.]


8. np.**copy**(array): khởi tạo bằng cách **copy từ array** khác

In [ ]:
import numpy as np

print("\n 8.np.copy(arr6_eye) ")
arr8_copy = np.copy(arr6_eye)
print(arr8_copy)



 8.np.copy(arr6_eye) 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


9. np.**reshape**(dim): khởi tạo từ **array vs dimensions**

In [ ]:
import numpy as np

print("\n 9.arr6_eye.reshape(3,4)")
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr9_reshape = arr.reshape(3,4) 

print(arr9_reshape)



 9.arr6_eye.reshape(3,4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


10. Các hàm random

In [ ]:
import numpy as np

print("\nCác hàm random")
print("\nmảng int [0,9) có size = dim")
print(np.random.randint(0,9, size=(5,5)))

print("\nmảng float [0,9) có size = dim")
print(np.random.uniform(0,9,size=(5,5)))

print("\ntrả về hoán vị [0,9), tham số có thể int or array")
print(np.random.permutation(10))

print("\n“standard normal” distribution có size = dim")
print(np.random.randn(5,5))


Các hàm random

mảng int [0,9) có size = dim
[[1 6 2 6 8]
 [3 5 1 8 7]
 [0 1 7 1 4]
 [7 8 8 5 2]
 [4 2 5 8 5]]

mảng float [0,9) có size = dim
[[8.78518115 3.88763992 3.66579447 8.68172679 8.15835121]
 [6.73627146 7.77866577 7.75450012 1.32714771 3.82608267]
 [7.20525251 2.18419945 8.46972146 4.74184093 3.57411794]
 [0.91154127 0.58609648 0.91297455 5.58867305 2.46537301]
 [2.55767323 4.87584853 1.67462985 8.25802101 2.76568637]]

trả về hoán vị [0,9), tham số có thể int or array
[8 3 2 7 9 4 1 5 0 6]

“standard normal” distribution có size = dim
[[-0.97405345  0.71198132  0.38788081 -2.33692111 -0.58403466]
 [-0.83977781 -0.86084346 -1.63723922  0.24910006 -0.95623727]
 [ 2.40978847  1.17417285 -0.95114195  0.00942998  1.20171189]
 [-0.5721559  -0.01730718 -1.25172904  1.26879907  1.64394345]
 [-1.36386929 -0.63903602 -0.70088948  0.2044703  -0.70854454]]


####**3.Truy vẫn dữ liệu**

In [ ]:
import numpy as np
a = np.arange(15).reshape(3, 5)
'''
Mảng sau khi tạo:
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])
'''
# Trả về: kích thước các trục (dimensions). Dimensions là 1 tuple.
print(a.shape) # >> (3, 5)

# Trả về: số chiều.
print(a.ndim) # >> 2

# Trả về: kiểu dữ liệu của mỗi phần tử.
print(a.dtype) # >> 'int64'

# Trả về: kích thước tính bằng byte của mỗi phần tử.
print(a.itemsize) # >> 8

# Trả về: độ dài của array
print(a.size) # >> 15

# Trả về: kiểu của mảng a
print(type(a)) # >> <class 'numpy.ndarray'>

(3, 5)
2
int64
8
15
<class 'numpy.ndarray'>


####**4. Indexing**

Numpy có thể được lập chỉ mục dạng x[**obj**]

Với obj:



1. basic slicing
2. advanced indexing
3. field access


*Slicing numpy tạo ra **VIEW** thay vì bản **COPY** như string, tuple và list.*

*Ngược lại với **Slicing**. **Advanced indexing** luôn trả về 1 bản **COPY**.*

#####**Slicing**

In [ ]:
import numpy as np

x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]).reshape(2,5)
'''
Mảng vừa tạo:
  [[0 1 2 3 4]
  [5 6 7 8 9]]
'''
x_n = x[0, 0:3]
x_n[0] = 999999
print(x)
print("\n",x_n)

[[999999      1      2      3      4]
 [     5      6      7      8      9]]

 [999999      1      2]


##### **Advanced indexing**

Với Advanced indexing thì obj:

* [ind1, ind2,...] ngăn cách bởi ','
* List positive integer
* List boolean (**Yêu cầu cùng số lượng phần tử**)
* narray
* Kết hợp các loại trên kể cả Basic slicing



In [ ]:
import numpy as np

x = np.array([0,1,2,3,4,5,6,7,8,9])


print("--- List positive integer ---")
print(x[[3,8,1,6]])


print("\n--- List boolean (Yêu cầu cùng số lượng phần tử) ---")
ind = x > 5
print(ind)
print(x[ind])


print("\n--- narray ---")
y = np.random.randint(0, 50, (50))
print(y[x])


print("\n--- [ind1, ind2,...] ngăn cách bởi ',' ---")
x = x.reshape(2,5)
print(x[1,1])


print("\n--- Kết hợp các loại trên kể cả Basic slicing ---")
print(x[1, 0:3])

--- List positive integer ---
[3 8 1 6]

--- List boolean (Yêu cầu cùng số lượng phần tử) ---
[False False False False False False  True  True  True  True]
[6 7 8 9]

--- narray ---
[ 7 47 37  5 40  2 45 19  4  8]

--- [ind1, ind2,...] ngăn cách bởi ',' ---
6

--- Kết hợp các loại trên kể cả Basic slicing ---
[5 6 7]


####**5.Phép toán và các hàm**

##### **+,-,*,/, dot**


Các phép +,-,*,/ thì: 

* phép tính của **các MA TRẬN** thì phải **cùng kích thước**
* phép tính của **MA TRẬN vs VECTOR** gọi là **Broadcasting** thì **Cột của MA TRẬN = độ dài VECTOR**

Riêng với phép tính dot thì:
* phép tính của **các MA TRẬN** thì **số cột MA TRẬN ĐẦU = số hàng MA TRẬN SAU**
* phép tính của **MA TRẬN vs VECTOR** thì **số cột MA TRẬN = độ dài VECTOR**

> **Broadcasting** thì VECTOR sẽ chồng lên **bằng số hàng vs ma trận**





In [ ]:
x1 = np.array([1,2,3,4,5,6,7,8,9,10]).reshape(2,5) # 2 hàng x 5 cột
x2 = np.array([-1,-2,-3,-4,-5,-6,-7,-8,-9,-10]).reshape(2,5) # 2 hàng x 5 cột
vector = np.array([1,2,3,4,5]) # 5 giá trị

print("--- MA TRẬN vs MA TRẬN ---")
print(x1 + x2)
print(x1 - x2)
print(x1 * x2)
print(x1 / x2)
print(x1.dot(x2.T)) # chuyển x2 sang kích thước 5x2

print("\n \n--- MA TRẬN vs VECTOR ---")
print(x1 + vector)
print(x1 - vector)
print(x1 * vector)
print(x1 / vector)
print(x1.dot(vector))


--- MA TRẬN vs MA TRẬN ---
[[0 0 0 0 0]
 [0 0 0 0 0]]
[[ 2  4  6  8 10]
 [12 14 16 18 20]]
[[  -1   -4   -9  -16  -25]
 [ -36  -49  -64  -81 -100]]
[[-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]]
[[ -55 -130]
 [-130 -330]]

 
--- MA TRẬN vs VECTOR ---
[[ 2  4  6  8 10]
 [ 7  9 11 13 15]]
[[0 0 0 0 0]
 [5 5 5 5 5]]
[[ 1  4  9 16 25]
 [ 6 14 24 36 50]]
[[1.         1.         1.         1.         1.        ]
 [6.         3.5        2.66666667 2.25       2.        ]]
[ 55 130]


*Phần này mình chưa biết phải làm thế nào nên sau khi tham khảo bài của anh Văn Quang mình xin phép để đường dẫn giống anh đấy ở đây để mọi người cùng tham khảo !*

##### **Hàm toán học**


Tham khảo: https://numpy.org/doc/stable/reference/routines.math.html

##### **Hàm Statistics**


Tham khảo: https://numpy.org/doc/stable/reference/routines.statistics.html


##### **Hàm Linear algebra**


Tham khảo: https://numpy.org/doc/stable/reference/routines.linalg.html

##### **Sorting, searching, and counting**


Tham khảo: https://numpy.org/doc/stable/reference/routines.sort.html

#####**Data Processing**

Tham khảo: https://numpy.org/doc/stable/user/basics.io.genfromtxt.html

---